#ifndef DSI_XML
#define DSI_XML

/* Autogenerated file, DO NOT EDIT manually!

This file was generated by the rules-ng-ng headergen tool in this git repository:
http://0x04.net/cgit/index.cgi/rules-ng-ng
git clone git://0x04.net/rules-ng-ng

The rules-ng-ng source files this header was generated from are:
- /home/robclark/src/freedreno/envytools/rnndb/msm.xml                 (    595 bytes, from 2013-07-05 19:21:12)
- /home/robclark/src/freedreno/envytools/rnndb/freedreno_copyright.xml (   1453 bytes, from 2013-03-31 16:51:27)
- /home/robclark/src/freedreno/envytools/rnndb/mdp4/mdp4.xml           (  18030 bytes, from 2013-07-05 19:21:12)
- /home/robclark/src/freedreno/envytools/rnndb/dsi/dsi.xml             (   6265 bytes, from 2013-07-05 19:21:12)
- /home/robclark/src/freedreno/envytools/rnndb/dsi/sfpb.xml            (    307 bytes, from 2013-07-05 19:21:12)
- /home/robclark/src/freedreno/envytools/rnndb/dsi/mmss_cc.xml         (   1622 bytes, from 2013-07-05 19:21:12)
- /home/robclark/src/freedreno/envytools/rnndb/hdmi/qfprom.xml         (    600 bytes, from 2013-07-05 19:21:12)
- /home/robclark/src/freedreno/envytools/rnndb/hdmi/hdmi.xml           (  19288 bytes, from 2013-07-05 19:21:12)

Copyright (C) 2013 by the following authors:
- Rob Clark <robdclark@gmail.com> (robclark)

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice (including the
next paragraph) shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE COPYRIGHT OWNER(S) AND/OR ITS SUPPLIERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#define DSI_IRQ_CMD_DMA_DONE					0x00000001
#define DSI_IRQ_MASK_CMD_DMA_DONE				0x00000002
#define DSI_IRQ_CMD_MDP_DONE					0x00000100
#define DSI_IRQ_MASK_CMD_MDP_DONE				0x00000200
#define DSI_IRQ_VIDEO_DONE					0x00010000
#define DSI_IRQ_MASK_VIDEO_DONE					0x00020000
#define DSI_IRQ_ERROR						0x01000000
#define DSI_IRQ_MASK_ERROR					0x02000000
#define REG_DSI_CNTL						0x00000000
#define DSI_CNTL_ENABLE						0x00000001
#define DSI_CNTL_VID_MODE_EN					0x00000002
#define DSI_CNTL_CMD_MODE_EN					0x00000004

#define REG_DSI_STATUS0						0x00000004
#define DSI_STATUS0_CMD_MODE_DMA_BUSY				0x00000002
#define DSI_STATUS0_VIDEO_MODE_ENGINE_BUSY			0x00000008
#define DSI_STATUS0_DSI_BUSY					0x00000010

#define REG_DSI_FIFO_STATUS					0x00000008

#define REG_DSI_VID_CFG0					0x0000000c

#define REG_DSI_VID_CFG1					0x0000001c

#define REG_DSI_CMD_DMA_CTRL					0x00000038

#define REG_DSI_CMD_CFG0					0x0000003c

#define REG_DSI_CMD_CFG1					0x00000040

#define REG_DSI_DMA_BASE					0x00000044

#define REG_DSI_DMA_LEN						0x00000048

#define REG_DSI_ACK_ERR_STATUS					0x00000064

static inline uint32_t REG_DSI_RDBK(uint32_t i0) { return 0x00000068 + 0x4*i0; }

static inline uint32_t REG_DSI_RDBK_DATA(uint32_t i0) { return 0x00000068 + 0x4*i0; }

#define REG_DSI_TRIG_CTRL					0x00000080

#define REG_DSI_TRIG_DMA					0x0000008c

#define REG_DSI_DLN0_PHY_ERR					0x000000b0

#define REG_DSI_TIMEOUT_STATUS					0x000000bc

#define REG_DSI_CLKOUT_TIMING_CTRL				0x000000c0

#define REG_DSI_EOT_PACKET_CTRL					0x000000c8

#define REG_DSI_LAN_SWAP_CTRL					0x000000ac

#define REG_DSI_ERR_INT_MASK0					0x00000108

#define REG_DSI_INTR_CTRL					0x0000010c

#define REG_DSI_RESET						0x00000114

#define REG_DSI_CLK_CTRL					0x00000118

#define REG_DSI_PHY_RESET					0x00000128

#define REG_DSI_PHY_PLL_CTRL_0					0x00000200

#define REG_DSI_PHY_PLL_CTRL_1					0x00000204

#define REG_DSI_PHY_PLL_CTRL_2					0x00000208

#define REG_DSI_PHY_PLL_CTRL_3					0x0000020c

#define REG_DSI_PHY_PLL_CTRL_4					0x00000210

#define REG_DSI_PHY_PLL_CTRL_5					0x00000214

#define REG_DSI_PHY_PLL_CTRL_6					0x00000218

#define REG_DSI_PHY_PLL_CTRL_7					0x0000021c

#define REG_DSI_PHY_PLL_CTRL_8					0x00000220

#define REG_DSI_PHY_PLL_CTRL_9					0x00000224

#define REG_DSI_PHY_PLL_CTRL_10					0x00000228

#define REG_DSI_PHY_PLL_CTRL_11					0x0000022c

#define REG_DSI_PHY_PLL_CTRL_12					0x00000230

#define REG_DSI_PHY_PLL_CTRL_13					0x00000234

#define REG_DSI_PHY_PLL_CTRL_14					0x00000238

#define REG_DSI_PHY_PLL_CTRL_15					0x0000023c

#define REG_DSI_PHY_PLL_CTRL_16					0x00000240

#define REG_DSI_PHY_PLL_CTRL_17					0x00000244

#define REG_DSI_PHY_PLL_CTRL_18					0x00000248

#define REG_DSI_PHY_PLL_CTRL_19					0x0000024c

#define REG_DSI_PHY_PLL_STATUS					0x00000280
#define DSI_PHY_PLL_STATUS_PLL_BUSY				0x00000001

static inline uint32_t REG_DSI_LN(uint32_t i0) { return 0x00000300 + 0x40*i0; }

static inline uint32_t REG_DSI_LN_CFG_0(uint32_t i0) { return 0x00000300 + 0x40*i0; }

static inline uint32_t REG_DSI_LN_CFG_1(uint32_t i0) { return 0x00000304 + 0x40*i0; }

static inline uint32_t REG_DSI_LN_CFG_2(uint32_t i0) { return 0x00000308 + 0x40*i0; }

static inline uint32_t REG_DSI_LN_TEST_DATAPATH(uint32_t i0) { return 0x0000030c + 0x40*i0; }

static inline uint32_t REG_DSI_LN_TEST_STR_0(uint32_t i0) { return 0x00000314 + 0x40*i0; }

static inline uint32_t REG_DSI_LN_TEST_STR_1(uint32_t i0) { return 0x00000318 + 0x40*i0; }

#define REG_DSI_PHY_LNCK_CFG_0					0x00000400

#define REG_DSI_PHY_LNCK_CFG_1					0x00000404

#define REG_DSI_PHY_LNCK_CFG_2					0x00000408

#define REG_DSI_PHY_LNCK_TEST_DATAPATH				0x0000040c

#define REG_DSI_PHY_LNCK_TEST_STR0				0x00000414

#define REG_DSI_PHY_LNCK_TEST_STR1				0x00000418

#define REG_DSI_PHY_TIMING_CTRL_0				0x00000440

#define REG_DSI_PHY_TIMING_CTRL_1				0x00000444

#define REG_DSI_PHY_TIMING_CTRL_2				0x00000448

#define REG_DSI_PHY_TIMING_CTRL_3				0x0000044c

#define REG_DSI_PHY_TIMING_CTRL_4				0x00000450

#define REG_DSI_PHY_TIMING_CTRL_5				0x00000454

#define REG_DSI_PHY_TIMING_CTRL_6				0x00000458

#define REG_DSI_PHY_TIMING_CTRL_7				0x0000045c

#define REG_DSI_PHY_TIMING_CTRL_8				0x00000460

#define REG_DSI_PHY_TIMING_CTRL_9				0x00000464

#define REG_DSI_PHY_TIMING_CTRL_10				0x00000468

#define REG_DSI_PHY_TIMING_CTRL_11				0x0000046c

#define REG_DSI_PHY_CTRL_0					0x00000470

#define REG_DSI_PHY_CTRL_1					0x00000474

#define REG_DSI_PHY_CTRL_2					0x00000478

#define REG_DSI_PHY_CTRL_3					0x0000047c

#define REG_DSI_PHY_STRENGTH_0					0x00000480

#define REG_DSI_PHY_STRENGTH_1					0x00000484

#define REG_DSI_PHY_STRENGTH_2					0x00000488

#define REG_DSI_PHY_BIST_CTRL_0					0x0000048c

#define REG_DSI_PHY_BIST_CTRL_1					0x00000490

#define REG_DSI_PHY_BIST_CTRL_2					0x00000494

#define REG_DSI_PHY_BIST_CTRL_3					0x00000498

#define REG_DSI_PHY_BIST_CTRL_4					0x0000049c

#define REG_DSI_PHY_LDO_CNTL					0x000004b0

#define REG_DSI_PHY_REGULATOR_CTRL_0				0x00000500

#define REG_DSI_PHY_REGULATOR_CTRL_1				0x00000504

#define REG_DSI_PHY_REGULATOR_CTRL_2				0x00000508

#define REG_DSI_PHY_REGULATOR_CTRL_3				0x0000050c

#define REG_DSI_PHY_REGULATOR_CTRL_4				0x00000510

#define REG_DSI_PHY_REGULATOR_CAL_PWR_CFG			0x00000518

#define REG_DSI_PHY_CAL_HW_TRIGGER				0x00000528

#define REG_DSI_PHY_CAL_SW_CFG_0				0x0000052c

#define REG_DSI_PHY_CAL_SW_CFG_1				0x00000530

#define REG_DSI_PHY_CAL_SW_CFG_2				0x00000534

#define REG_DSI_PHY_CAL_HW_CFG_0				0x00000538

#define REG_DSI_PHY_CAL_HW_CFG_1				0x0000053c

#define REG_DSI_PHY_CAL_HW_CFG_2				0x00000540

#define REG_DSI_PHY_CAL_HW_CFG_3				0x00000544

#define REG_DSI_PHY_CAL_HW_CFG_4				0x00000548

#define REG_DSI_PHY_CAL_STATUS					0x00000550
#define DSI_PHY_CAL_STATUS_CAL_BUSY				0x00000010


#endif /* DSI_XML */
